source 'https://github.com/CocoaPods/Specs.git'

target 'introspectre', :exclusive => true do
  pod "introspectre", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "introspectre", :path => "../"

  
end
